name: Sync Source to Source-only Mirror (Tazan)

on:
  push:
    branches: [ main ]
    paths:
      - 'Source/**'
      - 'Config/**'
      - 'Plugins/**'
      - 'Tazan.uproject'
      - 'Doc/**'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (sparse)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false
          sparse-checkout: |
            README.md
            Doc
            Source
            Config
            Plugins
            Tazan.uproject
          sparse-checkout-cone-mode: false

      - name: Prepare mirror workspace
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out
          [ -d "Source" ] && rsync -av --delete "Source/" "out/Source/" || true
          [ -d "Config" ] && rsync -av --delete "Config/" "out/Config/" || true
          if [ -d "Plugins" ]; then
            rsync -av --delete --include='*/' --include='*/Source/***' --exclude='*' "Plugins/" "out/Plugins/"
          fi
          [ -f "Tazan.uproject" ] && cp "Tazan.uproject" "out/Tazan.uproject" || true
          [ -d "Doc" ] && rsync -av --delete "Doc/" "out/Doc/" || true

          {
            echo "# Tazan.Source — source-only mirror"
            echo
            echo "> 이 리포는 **소스 코드 전용 미러**입니다."
            echo "> 전체 프로젝트(에셋 포함)와 **풀 README**는 원본 리포에서 확인하세요:"
            echo "> 👉 [Tazan (Main Repo)](https://github.com/${GITHUB_REPOSITORY%/*}/Tazan)"
            echo
            echo "포함: \`Source/\`, \`Config/\`, \`Plugins/*/Source\`, \`Tazan.uproject\`, \`Doc/\`"
            echo "제외: \`Content/\`, \`Binaries/\`, \`Intermediate/\`"
            echo
            echo "---"
            echo
            echo "<details><summary><b>Full README (from main repo)</b></summary>"
            echo
          } > out/README.md

          if [ -f "README.md" ]; then
            cat "README.md" >> out/README.md
          fi

          echo -e "\n</details>\n" >> out/README.md

      - name: Push to source-only repo
        working-directory: out
        env:
          MIRROR_REPO: ${{ secrets.TAZAN_SOURCE_REPO }}
          MIRROR_PAT:  ${{ secrets.TAZAN_SOURCE_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          [ -n "${MIRROR_REPO:-}" ] || { echo "MIRROR_REPO empty"; exit 1; }
          [ -n "${MIRROR_PAT:-}" ]  || { echo "MIRROR_PAT empty";  exit 1; }
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(mirror): sync from $GITHUB_SHA"
          git branch -M main
          git remote add origin "https://x-access-token:${MIRROR_PAT}@github.com/${MIRROR_REPO}.git"
          git ls-remote --heads origin >/dev/null
          git push -f origin main
